channels:
- bioconda
- conda-forge
dependencies:
- samtools=1.21
- salmon=1.11.4
- star=2.7.11b
- fastqc=0.12.1
- multiqc=1.35
- trim-galore=2.2.0
- cutadapt=5.2
- bedtools=2.31.1
- ucsc-bedgraphtobigwig=482
- pandoc=3.10
- tbb=2023.0.0
