channels:
- bioconda
- conda-forge
dependencies:
- samtools=1.22
- salmon=1.10.3
- star=2.7.10b
- fastqc=0.12.1
- multiqc=1.35
- trim-galore=0.6.11
- cutadapt=5.2
- bedtools=2.31.1
- ucsc-bedgraphtobigwig=482
- pandoc=3.10
- tbb=2023.0.0
- gzip=1.14
