on:
  push:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 9 * * 5'

name: snakemake-run

jobs:
  snakemake-run:
    name: run snakemake
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        include:
        - os: macos-latest
          rversion: '4.2'
        - os: ubuntu-latest
          rversion: '4.2'
    steps:
      - uses: actions/checkout@v2
      
      - uses: r-lib/actions/setup-r@master
        if: runner.os == 'macOS'
        with:
          r-version: ${{ matrix.rversion }}
      
      - name: check where R is installed
        if: runner.os == 'macOS'
        run: |
          which R
          Rscript -e 'print(.libPaths())'
      
      - name: set up workflow R for macOS
        if: runner.os == 'macOS'
        run: |
          sed -i .bak 's/useCondaR: True/useCondaR: False/' config.yaml
          mkdir -p $HOME/Rlib
          echo "R_LIBS_USER=${HOME}/Rlib" > .Renviron
          cat .Renviron
          Rscript -e "install.packages('BiocManager'); BiocManager::install('GenomeInfoDbData')"
          
      - name: setup conda
        uses: s-weigand/setup-conda@v1.1.0
        with:
          activate-conda: true
          update-conda: true
          conda-channels: 'bioconda,conda-forge,defaults'

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes 
          sudo apt-get --yes --force-yes update -qq && \
          sudo apt-get -y install libcairo2-dev libv8-dev \
          libgdal-dev libgeos-dev libgeos++-dev libproj-dev libudunits2-dev \
          libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libglpk-dev \
          libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev libgit2-dev

      - name: install snakemake and run workflow
        run: |
          conda install -c bioconda snakemake=6.10.0
          mkdir -p $HOME/.R
          echo -e 'MAKEFLAGS = -j8' > $HOME/.R/Makevars
          echo 'options(Ncpus = 8)' > $HOME/.Rprofile
          snakemake --use-conda --cores 4
      
      - name: upload artifact
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: all_rout
          path: example_data/output/Rout/*.Rout
